version: "3.9"

services:
  db:
    image: postgres:17
    container_name: nyc_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./mydb_dump.sql:/docker-entrypoint-initdb.d/mydb_dump.sql

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: nyc_backend
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:123@db:5432/mydb
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: nyc_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  pgdata:
